### ISSUE TITLE
如何设定图片上传自动居中

### ISSUE THREAD

**Issue by youhuiji** [cnblogs/vscode-cnb#133]
### 新功能描述

请问该如何设置可以让图片上传之后自动居中呢？
是否有这一部分的可配置选项呢？

**Comment by laggage** [comment]
如果是下图这种效果的居中的话，可以通过自定义css解决

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/38829279/232270637-9013ed9b-8da5-485d-8603-f906af039c80.png">

在[博客后台-设置-页面定制css](https://i.cnblogs.com/settings)加入下面的内容

```css
.blogpost-body p > img {
display: block;
margin: auto;
}
```
